version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: some-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: mon-application # Remplacez par l'image de votre application Spring Boot
    container_name: spring-boot-app
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/my_database
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_password
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  mysql_data:
